### ISSUE TITLE
core dump in to_array() function

### ISSUE THREAD

**Issue by mjabri** [arrayfire/arrayfire-python#10]
I am getting a core dump as follows

$ python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrayfire as af
Using cpu backend
>>> ar4=af.array()
>>> r4=ar4.to_array()
Segmentation fault (core dumped)
$

this is using ArrayFire i got from github 2 days ago and arrayfire-python got from github today. Note all tests of ArrayFire pass, and running all examples of arrayfire-python looks ok.

**Comment by pavanky** [comment]
@mjabri Looks like I should be throwing exceptions when you try to do "to_array()" from an empty array. You can try creating a random array and then see what happens.

Can you also explain what tests are failing on your system (in a separate issue perhaps)?

**Comment by mjabri** [comment]
tried with randu and randn ant seems to work. All tests after build are working ok. LAPACK issue was resolved as mentioned on GITTER.

**Comment by pavanky** [comment]
Fixed in master by raising exceptions when array is empty.
