### ISSUE TITLE
Core dumped using where function

### ISSUE THREAD

**Issue by krisrub** [arrayfire/arrayfire-python#107]
Using this code: 

```python
# array made by hand or by boolean expression
dA = af.constant(0,5) 
dPos = af.where(dA)
```
It aborts the python interpreter and you get a core dumped message, instead of an exception.

Info output:
```
ArrayFire v3.2.2 (OpenCL, 64-bit Linux, build )
[0] NVIDIA  : GeForce GTX 750 Ti OpenCL 1.2 CUDA Device driver 361.42 FP64 Support(True)
```

**Comment by pavanky** [comment]
@krisrub This has been fixed upstream a couple of versions ago. Can you upgrade both arrayfire and arrayfire-python and try again ?

**Comment by krisrub** [comment]
Hi
I have upgraded to version 3.4 and now it works great!
Thanks.
