### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire-python#11]
It would be nice to simply:
  - pip install arrayfire
or as an intermediary:
  - pip install git+https://github.com/arrayfire/arrayfire-python

I think all it needs is a setup.py

**Comment by pavanky** [comment]
duplicate of https://github.com/arrayfire/arrayfire-python/issues/8

**Comment by jramapuram** [comment]
Gah I need to read, sorry. Did a quick grep for pip and didnt see anything.

**Comment by pavanky** [comment]
@jramapuram It is now in master. Let me know if it works.
