### ISSUE TITLE
typo in nearest_neighbour function

### ISSUE THREAD

**Issue by vincentme** [arrayfire/arrayfire-python#111]
the nearest_neighbour function in vision.py called idx.arr, but the array initialized is index

**Comment by pavanky** [comment]
@vincentme do you want to send a PR or do you want me to fix it?

**Comment by vincentme** [comment]
Please go ahead do that. This is my first time report a bug, and not really sure how to fix it.

**Comment by pavanky** [comment]
@vincentme I am going to fix this, but for future reference you can follow this guide: 
https://github.com/arrayfire/arrayfire/wiki/Contribute-code-using-github

It was written for arrayfire library, but the same workflow applies to `arrayfire-python` as well.

**Comment by pavanky** [comment]
This has been fixed in devel.
