### ISSUE TITLE
Windows - Warning:  Program terminating, but clFFT resources not freed.

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire-python#115]
ArrayFire almost works well on Windows however I'm getting he following message on exit:

```
Warning:  Program terminating, but clFFT resources not freed.
Please consider explicitly calling clfftTeardown( ).
```

How and when should this method called from Python land?

**Comment by pavanky** [comment]
This is coming all the way up from clfft. This is because arrayfire does not call clftTeardown() on windows because a few architectures error out. Since It is just a warning we thought it was a fair trade off compared to getting a failure at exit.

**Comment by unbornchikken** [comment]
How could this warning be suppressed at Python side?

**Comment by pavanky** [comment]
@unbornchikken it can't
