### ISSUE TITLE
Interop support for Numba?

### ISSUE THREAD

**Issue by AviKav** [arrayfire/arrayfire-python#122]

**Comment by pavanky** [comment]
@AviKav Although I have heard of them, I have never used anaconda or numba before. Can you tell me how you think the interop should work ?

**Comment by pavanky** [comment]
@AviKav From what I can see numba does not have the ability to create arrays from existing device pointers. It also doesn't return device pointers so users can copy to it manually. Any support we add now will have to do a costy two way transfer (arrayfire --> numpy --> Numba).

Unless I am wrong, you will have to create an issue on Numba to support external CUDA libraries.

**Comment by pavanky** [comment]
Nevermind, I found `DeviceNDArray` which seems like it should do the trick.

**Comment by pavanky** [comment]
@AviKav I added support to create arrayfire arrays from numba arrays similar to what is happening for numpy and PyCUDA. I'll need to add functions to go in the other direction. 

I am closing this issue and dealing with the reverse transfers over here: 
https://github.com/arrayfire/arrayfire-python/issues/128
