### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire-python#13]
- [ ] [incorrectly assigning to module](https://github.com/arrayfire/arrayfire-python/blob/v3.0/arrayfire/array.py#L19?)
- [ ] create_array should use `c_void_p` instead of `c_ulonglong`
- [ ] arrayfire.array class and file being the same may cause conflicts

**Comment by FilipeMaia** [comment]
There are a lot of unnecessary backslashes at the end of line (I haven't seen any that's necessary).
They should be removed, as it goes against the python style guide.
