### ISSUE TITLE
Possible bug in af.approx1()

### ISSUE THREAD

**Issue by ShyamSS-95** [arrayfire/arrayfire-python#130]
I've written a file comparing the results of the interpolate function in scipy libraries, and arrayfire:

http://nbviewer.jupyter.org/gist/ShyamSS-95/9267f7f860f4ce5aa5ea785c937bbfda

I don't seem to be getting the same result for both the functions.
`af.approx1()` seems to be quite off from the expected curve.

Is there a bug here?

**Comment by pavanky** [comment]
@ShyamSS-95 can you plot `asin(interpolated - actual)` ?

**Comment by pavanky** [comment]
@ShyamSS-95 wait that wouldn't work. I keep forgetting my trigonometric formulas :) It looks like the two curves are phase shifted. I'll investigate it once I get home.
