### ISSUE TITLE
library import mismatch libforge.so.3 <=> libforge.so.0

### ISSUE THREAD

**Issue by jcmgray** [arrayfire/arrayfire-python#131]
Currently, (with the most recent linux 64-bit binary install of arrayfire and devel branch of `arrayfire-python`), `libforge.so`/`libforge.so.0` is created under `$AF_PATH/lib/` but `arrayfire.library._clibrary.__init__` searches for `libforge.so.3` and cannot find it - preventing `import arrayfire`. For the moment creating a soft link fixes the issue and everything runs fine.

**Comment by pavanky** [comment]
@jcmgray Thanks for finding the bug! Do you want to send in a PR to fix it ?

**Comment by jcmgray** [comment]
Sure thing, I've put something together in #132. Abstracting out the major version numbers seemed like the best thing to do, but let me know the if the string replacement thing is a bit hacky.

Also only tested on linux so far.

**Comment by pavanky** [comment]
> Also only tested on linux so far.

That should be fine :D
