### ISSUE TITLE
Feature/function request

### ISSUE THREAD

**Issue by TejasMane** [arrayfire/arrayfire-python#133]
Currently, the histogram functions available in `arrayfire.graphics` and `arrayfire.image` don't support the options of `weights` unlike the histogram function available in  numpy libraries. [https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html](url). It would be great if a function similar to the `numpy.histogram` is available in Arrayfire as well.

**Comment by pavanky** [comment]
@TejasMane That is a feature request for the arrayfire library. Can you open it here: https://github.com/arrayfire/arrayfire

**Comment by TejasMane** [comment]
ok.
