### ISSUE TITLE
Assignment changes values copied, CPU

### ISSUE THREAD

**Issue by pthon** [arrayfire/arrayfire-python#138]
Array value assignment changes the copied values when running on CPU using python wrapping:

*a=af.randu(2,2,2)
print a[1]
a[0] =a[1]
print a[1]*

After the assignment, the values of *a[1]* changed unexpectedly. This behaviour is not observed running on CUDA backend.
I am using ArrayFire v3.5.0 (CPU, 64-bit Linux, build 251e942) on Intel(R) Xeon(R) CPU E5-2630 0 and the current python wrapper development version.

**Comment by pavanky** [comment]
@pthon this was a bug in upstream arrayfire. It's been fixed and is available in the devel branch.
