### ISSUE TITLE
Need explanation on when to to use af.eval() and af.sync()

### ISSUE THREAD

**Issue by itsnarsi** [arrayfire/arrayfire-python#140]
I am using a function which uses af.broadcast inside it.

When I use the program in windows PC, I do not see any slowdown of the processing using CPU. However, when I use my linux PC which has both CPU and AMD RX 480 GPU, I see the code slow down drastically.

In [Issue#123](https://github.com/arrayfire/arrayfire-python/issues/123#issuecomment-278373628) @pavanky mentioned that to use af.eval and af.sync when using broadcast function. 

Can any one given me a simple explanation of this if possible.

Thanks

**Comment by itsnarsi** [comment]
Ok I need to backup and given proper explanation of what I am doing:
I am trying to create a AutoDifferentiation on top of arrayfire.
[LearnAF](https://github.com/itsnarsi/LearnAF)

- I was able to successfully create the outline and was able to execute it properly.

- Then I went on to create a MLP using this auto-encoder. Started working successfully on my windows PC(CPU only i7 6th gen).

[Jupyter Notebook](https://github.com/itsnarsi/LearnAF/blob/master/Layers.ipynb)

- I have another PC with i7 6th gen and RX 480. When I test both CPU and GPU('opencl'), as the batches go by the  speed reduces drastically.

problems at: [matmul](https://github.com/itsnarsi/LearnAF/blob/master/LearnAF/ops/matops.py)
[broadcast and unbroadcast](https://github.com/itsnarsi/LearnAF/blob/master/LearnAF/ops/autograd.py)


PS: Sorry for bad syntax and no comments, I'm just still in very starting stages of the code.

**Comment by pavanky** [comment]
Hmm, you definitely do not need `af.eval` or `af.sync` in your case.

**Comment by itsnarsi** [comment]
Can you help me understand exactly how they work?

**Comment by umar456** [comment]
@itsnarsi I sent you an explanation of the two functions on gitter.

**Comment by itsnarsi** [comment]
@umar456 thanks for the info.

I'll try to implement these in my code and let you guys know.

Thanks

**Comment by itsnarsi** [comment]
@umar456 @pavanky Ok damn. I modified code to with af.eval() and af.sync() and now on PC the performance literally double!!! (Close to Keras + Tensorflow on CPU)
![Windows](https://cloud.githubusercontent.com/assets/11802437/26223173/94e6e8b2-3be2-11e7-8691-65c6a5556f94.png)

While on linux I see a improvement on PC, but it is not what I hoped for.
Then: 
![Then](https://cloud.githubusercontent.com/assets/11802437/26223154/8062256e-3be2-11e7-9866-dfb8b046a09f.png)

**New:**
![New](https://cloud.githubusercontent.com/assets/11802437/26223229/d571ce6a-3be2-11e7-84b2-37b93ebf64d5.png)

Is there any reason for this to happen?
When it comes to 'opencl', the code is still lagging behind a lot.

**Comment by pavanky** [comment]
@itsnarsi I'll give it a try once I get home. Ping me if I don't respond in a couple of days.

**Comment by pavanky** [comment]
@itsnarsi can you point me to the script / file you are running as well as the output of `af.info()` from both machines ?

**Comment by itsnarsi** [comment]
Notebook I'm running: [Here](https://github.com/itsnarsi/LearnAF/blob/master/Layers.ipynb)

My Windows PC:
>>> af.info()
ArrayFire v3.4.2 (CPU, 64-bit Windows, build 2da9967)
[0] AMD     : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 32669 MB

Linux:
>>> af.info()
ArrayFire v3.4.1 (OpenCL, 64-bit Linux, build b9055b1)
[0] AMD     : Ellesmere, 7731 MB
-1- AMD     : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, 15996 MB

**Comment by pavanky** [comment]
@itsnarsi can you install `3.4.2` on your Linux machine as well ? I had a couple of JIT related fixes in 3.4.2 that may explain some of this.

**Comment by itsnarsi** [comment]
@pavanky as soon as I posted it I realized that I did not update my arrayfire in linux.

Sorry, I will do that and send you the results as soon as possible.

**Comment by itsnarsi** [comment]
@pavanky Ok Thanks for remaining me to update.
CPU on both linux and windows are working as needed.
**Same as windows in linux NOW!!**
![1](https://cloud.githubusercontent.com/assets/11802437/26225458/e42dc04e-3bec-11e7-9b0c-0c77d2a01279.png)


In case of 'opnecl' on my RX 480: 
![2](https://cloud.githubusercontent.com/assets/11802437/26225531/2c805e6a-3bed-11e7-99d4-91c01836bdc9.png)

- First epoch gave really low iterations but after that I got around 90 batches per second.

**Comment by pavanky** [comment]
If I am reading this correctly you are getting 96 batches / s on the GPU but you are getting 325 batches / s on the CPU ?

**Comment by pavanky** [comment]
@itsnarsi are you using floats or doubles for your experiment?

**Comment by itsnarsi** [comment]
@pavanky I am converting a float32 numpy to af.array using 'af.np_to_af_array' in all cases.

**Comment by pavanky** [comment]
@itsnarsi I am also unsure when the data copy occurs. If you are constantly copying data to the GPU then the times may be skewed because of this.

**Comment by pavanky** [comment]
@itsnarsi sent you a personal message on gitter can you reply to me there :)
