### ISSUE TITLE
Image processing and Vision functions are ported like the ArrayFire Julia lib?

### ISSUE THREAD

**Issue by QuantScientist** [arrayfire/arrayfire-python#149]
For instance, 
(https://github.com/JuliaComputing/ArrayFire.jl)

**Image Processing:**
scale, hist
loadImage, saveImage
isImageIOAvailable
colorspace, gray2rgb, rgb2gray, rgb2hsv, rgb2ycbcr, ycbcr2rgb, hsv2rgb
regions, SAT
bilateral, maxfilt, meanshift, medfilt, minfilt, sobel, histequal
resize, rotate, skew, transform, transformCoordinates, translate
dilate, erode, dilate3d, erode3d, gaussiankernel

**Computer Vision**

orb, sift, gloh, diffOfGaussians, fast, harris, susan, hammingMatcher, nearestNeighbour, matchTemplate

**Comment by pavanky** [comment]
@QuantScientist all these functions are supported in the python wrapper.

- http://arrayfire.org/arrayfire-python/arrayfire.image.html#module-arrayfire.image
- http://arrayfire.org/arrayfire-python/arrayfire.vision.html#module-arrayfire.vision
