### ISSUE TITLE
Missing array.device() function

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire-python#15]
I would like to able to get the device pointer like `array.device()` or `af_get_device_ptr()`.

**Comment by pavanky** [comment]
This is not possible without inter operating with PyCUDA and PyOpenCL. I do not want to add any non default dependencies to arrayfire. 

Do you have any suggestions about how you can do this?

**Comment by FilipeMaia** [comment]
I just wanted you to add something like:
```
def device(self):
    ptr = ctypes.c_void_p(0)
    arrayfire_python.clib.af_get_device_ptr(ctypes.pointer(ptr), self.arr)
    return ptr.value
```

**Comment by pavanky** [comment]
Alright, we can make that work

**Comment by pavanky** [comment]
I will probably call it `device_ptr` to make it explicit.

**Comment by FilipeMaia** [comment]
Sure, makes sense.
