### ISSUE TITLE
af.info() in the wrong window

### ISSUE THREAD

**Issue by gul916** [arrayfire/arrayfire-python#157]
Hello,
That is just a minor bug, but it can be disturbing.

When you are using spyder graphical interface in anaconda, `af.info()` is not reported in spyder window but rather in the shell that started it. However, `af.get_backend()` and `af.get_device()` are reporting in spyder window.

Example:
```python
import arrayfire as af

af.info()

af.get_backend()
Out[3]: 'unified'

af.get_device()
Out[4]: 0
```

Thanks for all your work.

**Comment by pavanky** [comment]
@gul916 `af.info()` prints to stdandard output. It doesn't return a string so it is not visible. You can use `af.info_str()` which is an equivalent function to print in a notebook or spyder window.

**Comment by gul916** [comment]
Thank you for your quick reply. `af.info_str()` works fine. All is on one line, but it is not due to arrayfire. Maybe do you know how to solve it ?

**Comment by pavanky** [comment]
@gul916 Use `print(af.info_str())` Do not rely on the repl to print it properly.

**Comment by gul916** [comment]
Thanks, you were faster than me !
