### ISSUE TITLE
remainder function giving negative result (af.rem)

### ISSUE THREAD

**Issue by matkraj** [arrayfire/arrayfire-python#180]
Hi, I noticed if I calculate reminder function I get:
`print(af.rem(af.constant(11,1,1),3))
`
> -1

which should be:
> 2

**Comment by pavanky** [comment]
@matkraj I think you should be looking at `af.mod`. This behavior is consistent with IEE (check [std::remainder](http://en.cppreference.com/w/cpp/numeric/math/remainder))

**Comment by matkraj** [comment]
@pavanky Thanks, I got confused because there is no af.mod in arrayfire-python.

**Comment by matkraj** [comment]
Probably this needs to be added to arrayfire/arith.py
```
def mod(lhs, rhs):
    """
    Find the modulus.
    Parameters
    ----------
    lhs : af.Array or scalar
          Multi dimensional arrayfire array or a scalar number.
    rhs : af.Array or scalar
          Multi dimensional arrayfire array or a scalar number.
    Returns
    --------
    out : af.Array
         Contains the moduli after dividing each value of lhs` with those in `rhs`.
    Note
    -------
    - Atleast one of `lhs` and `rhs` needs to be af.Array.
    - If `lhs` and `rhs` are both af.Array, they must be of same size.
    """
    return _arith_binary_func(lhs, rhs, backend.get().af_mod)
```

**Comment by pavanky** [comment]
@matkraj Do you want to send in a review with this change ?

**Comment by matkraj** [comment]
pull request https://github.com/arrayfire/arrayfire-python/pull/181
