### ISSUE TITLE
ArrayFire tests fail at LAPack

### ISSUE THREAD

**Issue by rwatkins77** [arrayfire/arrayfire-python#184]
Trying to install arrayfire for CUDA on pop os 18.1.   Tests of arrayfire fails at laPACK.  Calculation of pi also fails at af.count()   Any ideas?   Have I left out dependencies?  I followed the installation instructions and everything else is working.  Output of arrayfire.tests attached.

Simple        algorithm: PASSED
Simple            arith: PASSED
Simple            array: PASSED
Simple             blas: PASSED
Simple             data: PASSED
Simple           device: PASSED
Simple            image: PASSED
Simple            index: PASSED
Simple          interop: PASSED
Simple           lapack: FAILED
arrayfire.Array()
Type: float

[5 5 1 1]
    1.0000     0.0000     0.0000     0.0000     0.0000 
    0.8109     1.0000     0.0000     0.0000     0.0000 
    0.3003     0.9442     1.0000     0.0000     0.0000 
    0.8348    -0.6325     0.0729     1.0000     0.0000 
    0.6034     0.0700    -0.6864     0.9125     1.0000 

arrayfire.Array()
Type: float

[5 5 1 1]
    0.7467     0.4457     0.8635     0.1308     0.2734 
    0.0000     0.4954    -0.3161     0.8884     0.5619 
    0.0000     0.0000     0.2414    -0.0377     0.1674 
    0.0000     0.0000     0.0000     0.7634     0.3503 
    0.0000     0.0000     0.0000     0.0000    -0.4085 

arrayfire.Array()
Type: int

[5 1 1 1]
         4 
         0 
         2 
         3 
         1 

arrayfire.Array()
Type: float

[5 5 1 1]
    0.7467     0.4457     0.8635     0.1308     0.2734 
    0.8109     0.4954    -0.3161     0.8884     0.5619 
    0.3003     0.9442     0.2414    -0.0377     0.1674 
    0.8348    -0.6325     0.0729     0.7634     0.3503 
    0.6034     0.0700    -0.6864     0.9125    -0.4085 

arrayfire.Array()
Type: int

[5 1 1 1]
         4 
         0 
         2 
         3 
         1 

ERROR:root:Traceback (most recent call last):
  File "/home/rwatkins/anaconda3/lib/python3.6/site-packages/arrayfire/tests/simple/_util.py", line 32, in run
    test(verbose)
  File "/home/rwatkins/anaconda3/lib/python3.6/site-packages/arrayfire/tests/simple/lapack.py", line 31, in simple_lapack
    q,r,t = af.qr(a)
  File "/home/rwatkins/anaconda3/lib/python3.6/site-packages/arrayfire/lapack.py", line 101, in qr
    safe_call(backend.get().af_qr(c_pointer(Q.arr), c_pointer(R.arr), c_pointer(T.arr), A.arr))
  File "/home/rwatkins/anaconda3/lib/python3.6/site-packages/arrayfire/util.py", line 79, in safe_call
    raise RuntimeError(to_str(err_str))
RuntimeError: In function void cuda::qr(cuda::Array<T>&, cuda::Array<T>&, cuda::Array<T>&, const cuda::Array<T>&) [with T = float]
In file src/backend/cuda/qr.cu:169
CUBLAS Error (3): CUSOLVER_STATUS_INVALID_VALUE

Simple           signal: PASSED
Simple       statistics: PASSED
Simple           random: PASSED
Simple           sparse: PASSED

**Comment by pavanky** [comment]
@rwatkins77 The tests are not super reliable. Can you try using `qr` on a normal array to see if it works ?

**Comment by pavanky** [comment]
@rwatkins77 can you show the error when you are calculating pi ?

**Comment by rwatkins77** [comment]
We were having problems with the cuda-toolkit and thought that we fixed them.   Things (including the pi program)  now work in command line python or ipython but not in spyder, where it doesn't detect the toolkit.   This seems to be the source of the problem

**Comment by matkraj** [comment]
I have the same problem in `ipython3 -m arrayfire.tests` 
Could be related to issue https://github.com/arrayfire/arrayfire-python/issues/183

**Comment by pavanky** [comment]
@matkraj Can we move the conversation to the other issue ?
