### ISSUE TITLE
set_intersect not working with ParallelRange

### ISSUE THREAD

**Issue by crpacheco** [arrayfire/arrayfire-python#185]
Hi

Suppose I have a matrix M, a vector V and I want to intersect each row of M with V.
If I use the classic for

```
for i in range(M.shape[0]):
      af.set_intersect(M[i],V)
```

It works very well, but if I use the parallel for

```
for i in af.ParallelRange(M.shape[0]):
      af.set_intersect(M[i],V)
```

It fails with the next error message:

**Invalid argument at index 1
Expected: (first_info.isVector() || first_info.isScalar())**

Note: using af.broadcast instead of parallel for gives the same error message.

What can I do to solve this issue?

Thanks!

**Comment by pavanky** [comment]
@crpacheco The output size of set operations is based on the data inside the input array. You cant run this in parallel and generate an array of a fixed size.
