### ISSUE TITLE
Convert af.array into numpy array 

### ISSUE THREAD

**Issue by kareem1925** [arrayfire/arrayfire-python#204]
Is there a way to convert af arrays to numpy because i want to use the bilateral filter in arrayfire and then use the matrix again with opencv

**Comment by mark-poscablo** [comment]
Hi @kareem1925, an Array object in Python has a method called `to_ndarray()`. This should do the job. Please see the [documentation](http://arrayfire.org/arrayfire-python/arrayfire.array.html?highlight=to_ndarray#arrayfire.array.Array.to_ndarray) for more details.

**Comment by kareem1925** [comment]
i'm sorry to be late. thanks a lot for your reply
