### ISSUE TITLE
View AST/kernels

### ISSUE THREAD

**Issue by r-barnes** [arrayfire/arrayfire-python#209]
Is there any sort of debug mode that would allow one to view the ASTs or the resulting kernels?

**Comment by 9prady9** [comment]
@r-barnes Do you mean JIT kernels ?

**Comment by 9prady9** [comment]
Please note that this new environment variable is not yet available in 3.6.4 release.

**Comment by 9prady9** [comment]
Please close the issue if you are question has been answered.

**Comment by r-barnes** [comment]
I think this'll do what I need. I'll try to test sometime this week and report back.

**Comment by r-barnes** [comment]
To clarify, you mean master of arrayfire proper, not arrayfire-python, which hasn't been committed to lately.

**Comment by r-barnes** [comment]
This works pretty great, thanks.
