### ISSUE TITLE
Path error on MacOS (easy fix!)

### ISSUE THREAD

**Issue by miketrumpis** [arrayfire/arrayfire-python#217]
I installed the ArrayFire "pkg" installer for v3.6.4, which installs to /opt/arrayfire. After a long time trying to debug my "RuntimeError: Could not load any ArrayFire libraries.", I realized that the hard-coded path is simply wrong!

https://github.com/arrayfire/arrayfire-python/blob/aead0394ffda9bd820279f59a84a9dcba6e3691f/arrayfire/library.py#L492-L500

I changed this to the correct path, and tests are passing. More than happy to make a PR, but it's a pretty trivial fix :)

**Comment by umar456** [comment]
That would be wonderful!
