### ISSUE TITLE
Can add an af.multiply for two matrix or vector element-wise multiply?

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire-python#226]
Feature request.

**Comment by syurkevi** [comment]
Elementwise multiplication can be performed as follows:
```
import arrayfire as af
a = af.randu(3, 3)
b = af.randu(3, 3)
a * b
```
A full list of overloaded operators can be found in the array class here: https://github.com/arrayfire/arrayfire-python/blob/master/arrayfire/array.py
Unfortunately, these operators seem to be missing from the documentation...

**Comment by xichaoqiang** [comment]
Yes.It works.
