### ISSUE TITLE
array[0:0] should return empty array

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire-python#26]
Currently it is equivalent to array[:] which is quite surprising.

**Comment by FilipeMaia** [comment]
As empty arrays don't really exist yet a good compromise might to to return None.

**Comment by pavanky** [comment]
They do exist. `array(dim4())` is an empty array in ArrayFire. The functions can't handling them properly is a different issue..

**Comment by pavanky** [comment]
This is partially solved when using logical indexing in devel.

**Comment by pavanky** [comment]
This is fixed in devel.
