### ISSUE TITLE
Indexing errors inconsistent with C++

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire-python#28]
The following example shows the different behaviour in C++ and python:

```
#include <arrayfire.h>
int main(){
  af::array a = af::randu(3);
  af_print(a(af::span,0));
}
```

This will run fine on C++ but will raise an `IndexError` in python. I think it would be better if they both worked or both returned an error.

**Comment by pavanky** [comment]
@FilipeMaia The python wrapper exhibits behavior typical to python. There is no standard version for such indexing in C++ so we had to make up stuff as we went along. I do not think we should expect consistent behavior across C++ and Python in this regard.

**Comment by FilipeMaia** [comment]
The issue is related to the array dropping dimensions when one of the indices is a number. This is exactly the same in C++ and Python but by not raising an error in C++ is allow some more natural code.

Consider the following example:

```
import arrayfire as af
import numpy as np

a = af.randu(3,2)
rows = np.array([0],dtype=np.int32)
rows = af.Array(rows.ctypes.data,rows.shape,rows.type_char='i')
b = a[:,rows]
for r in rows:
  af.display(b[:,r])
```
Depending on the number of rows this might raise an error, which is not very intuitive.

**Comment by pavanky** [comment]
Can you post some working code sample that I can run to understand this better? The code you posted here does not work.

**Comment by pavanky** [comment]
There was a minor typo, fixed and and ran to see the problem. I am going to emulate the numpy behavior for this case.

**Comment by pavanky** [comment]
Having said that numpy treats 1D arrays differently than 2D arrays with second dimension == 1. I do not think supporting this behavior is possible in arrayfire.

We can treat the array as always being n-dimensional (like we do in C++) and or keep the current behavior.

I think reverting it back to the C++ like behavior is the more saner option of the two like you suggested.

@FilipeMaia Let me know if you have further suggestions.

**Comment by pavanky** [comment]
Fixed in master.

**Comment by FilipeMaia** [comment]
Sorry, I didn't test the code because of the seg fault on the for loop.
I agree, the C++ like behaviour is the better solution. Thanks for fixing it!
