### ISSUE TITLE
iterating over array causes seg fault

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire-python#29]
Doing `for in row in A:` currently causes a seg fault, I think due to IndexError not being raised when accessing outside the array.

**Comment by pavanky** [comment]
I just pushed [this commit](https://github.com/arrayfire/arrayfire-python/commit/b43deb5b9cc84dda6e4c6e18fb934ab401e1cdf0) that was causing segfaults earlier.

Can you check if this is still happening with HEAD?

**Comment by FilipeMaia** [comment]
You're right, it fixed it!
