### ISSUE TITLE
Could not load any ArrayFire cuda backend

### ISSUE THREAD

**Issue by marbre** [arrayfire/arrayfire-python#39]
I know, the python bindings are not intended for production use. Anyway, I noticed that I can load the opencl and the cpu backend, but I am unable to load the cuda backend:

~~~
Python 3.4.1 (default, Oct 24 2014, 12:45:16) 
[GCC 4.7.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrayfire as af
>>> af.info()
ArrayFire v3.1.1 (OpenCL, 64-bit Linux, build )
[0] NVIDIA  : GeForce GTX 650 Ti 
-1- INTEL   : Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz 
>>> 
>>> af.backend.set( "cuda" )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/arrayfire/library.py", line 59, in set
    raise RuntimeError("Could not load any ArrayFire %s backend" % name)
RuntimeError: Could not load any ArrayFire cuda backend
>>> 
>>> af.backend.set( "cpu" )
>>> af.info()
ArrayFire v3.1.1 (CPU, 64-bit Linux, build )
[0] Intel: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz Max threads(4)
~~~

arrayfire was compiled with the CUDA toolkit 7.5.18.

**Comment by shehzan10** [comment]
Can you confirm whether the the CUDA nvvm/lib64 path is in you LD_LIBRARY_PATH?

**Comment by pavanky** [comment]
@marbre You need to set `LD_LIBRARY_PATH` to point to cuda/nvvm/lib64 as well.

**Comment by pavanky** [comment]
> I know, the python bindings are not intended for production use. 

Oops, I forgot to remove that from description. I think it is more or less stable right now.

**Comment by marbre** [comment]
Okay, that did the trick. Is this documented somewhere?

**Comment by pavanky** [comment]
@marbre It is supposed to be documented here: https://github.com/arrayfire/arrayfire-python/wiki

But I realize I did not add the part about nvvm. I will be adding it.

**Comment by pavanky** [comment]
That page is linked from the main README.md under the getting_started section. I can perhaps add the link to the page in the error messasge.

**Comment by marbre** [comment]
@pavanky I checked this page of cause, but it only states the the arrayfire library has to be in the library path, which is the case on my system. Furthermore, also libcudart is in the library path, but libnvvm wasn't.

**Comment by pavanky** [comment]
@marbre I updated it now. Thanks for bringing it up. Usually most distros put  `CUDA_PATH/lib64` in the system path but skip `CUDA_PATH/nvvm/lib64`

This is also true for the CUDA installer on windows.

**Comment by marbre** [comment]
@pavanky That was actually the problem here, so thanks for your support. I'll push this change to Gentoo.
