### ISSUE TITLE
af.display is broken in release 3.0.20150914

### ISSUE THREAD

**Issue by marbre** [arrayfire/arrayfire-python#40]
I tested the current master and also 3.0.20150914 (available via pypi). In 3.0.20150914 `af.display(a)` (taken from the example) doesn't shows any output, with the current master the the output is as expected. I assume this was fixed with commit 80d299d.

Maybe, a new release could be created?

**Comment by pavanky** [comment]
@marbre This is only broken when running from the interpreter. If you run it as a script and / or ipython it works. 

I can make a new release with a couple of fixes.

**Comment by marbre** [comment]
@pavanky Could you please provide a more recent release? I would like to add a more recent relase to the Gentoo [science overlay](https://github.com/gentoo-science/sci/tree/master/dev-python/arrayfire-python).
Furthermore, the note `This is a work in progress and is not intended for production use.` should be removed from the README.md.

**Comment by pavanky** [comment]
@marbre This is now done with 3.1.20151111

**Comment by marbre** [comment]
@pavanky Thanks for taking care :)

Just version bumped it in Gentoo science overlay https://github.com/gentoo-science/sci/commit/eae237c0cc669b54765418d89b4b48ee86130fb3.
