### ISSUE TITLE
arrayfire.flat() creating a copy

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire-python#45]
```python
import arrayfire
a = arrayfire.randu(3,2)
a.device_ptr()
>>> 30068441088
b = a[:,:]
b.device_ptr()
>>> 30068441088 
# all fine until this point
arrayfire.flat(b).device_ptr()
>>> 30068442112
# here's trouble!
```
Using a one-dimensional array does not cause a copy. Calling `flat()` on `a` does not cause a copy. I'm not certain if this is a bug, but it's certainly surprising. Also it probably comes from arrayfire directly.

**Comment by pavanky** [comment]
Hmm. This does not seem to happen in C++ using the following code:

```
        array a = randu(5,5);
        array b = a(span);
        array c = flat(b);
        printf("%p, %p, %p\n", a.device<float>(), b.device<float>(), c.device<float>());
```

**Comment by pavanky** [comment]
OK, I am able to reproduce this in C++ using the following:

```
    array a = randu(5,5);
    array b = a(seq(5), seq(5));
    array c = flat(b);
    printf("%p, %p, %p\n", a.device<float>(), b.device<float>(), c.device<float>());
```

I **think** I know how to fix this, but I am not sure it will make it to 3.2.0 because it requires additional testing.

**Comment by pavanky** [comment]
Created an issue upstream over here: https://github.com/arrayfire/arrayfire/issues/1101

**Comment by FilipeMaia** [comment]
It would be important to also take into account the case where `array b` is not the entire `array a` but a contiguous subset. Like:

```python
import arrayfire
a = arrayfire.randu(3,4)
a.device_ptr()
>>> 30068445184
b = a[:,:2]
# This is great
b.device_ptr()
>>> 30068445184
# Problem is here
arrayfire.flat(b).device_ptr()
>>> 30068446208
```

**Comment by pavanky** [comment]
This bug is fixed upstream. However calling `device_ptr` might cause a copy. Use `device_mem_info()` to check if new buffers are locked as an alternative.

The next release of arrayfire will have new functions that will improve the situation further.
