### ISSUE TITLE
use af_info_string for arrayfire.info

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire-python#50]
This can only make it to master after upstream fixes [this issue](https://github.com/arrayfire/arrayfire/issues/1159)

**Comment by pavanky** [comment]
@mchandra Watch this issue!

**Comment by mchandra** [comment]
Thanks!

**Comment by mchandra** [comment]
Thanks!

**Comment by pavanky** [comment]
@mchandra I added a new function called `af.info_str()` that will return similar information from `af.info()`. This was done using existing functions such as `af.device_info()`.

I'll update the function to use the native method when arrayfire `3.3.0` is released. I am closing the issue now. If you still think it needs to be open, let me know.

**Comment by mchandra** [comment]
Thank you, that'll do for now.

**Comment by pavanky** [comment]
Btw this is available via master as well as the latest Pypi package.
