### ISSUE TITLE
Interoperability with numpy

### ISSUE THREAD

**Issue by cmey** [arrayfire/arrayfire-python#6]
Would it be possible to support interoperability with numpy?

```
import numpy as np
import arrayfire as af

A = np.zeros((2,3), dtype=np.complex64)
Ad = af.array(A) # <-- load data from a numpy array
af.display(Ad)
print(Ad.elements(), Ad.type(), Ad.dims(), Ad.numdims())
```

Currently:
```
Using opencl backend
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-c8c7947108da> in <module>()
      3 
      4 A = np.zeros((2,3), dtype=np.complex64)
----> 5 Ad = af.array(A) # <-- load data from a numpy array
      6 af.display(Ad)
      7 print(Ad.elements(), Ad.type(), Ad.dims(), Ad.numdims())

/Users/cmey/Code/GitHub/arrayfire-python/arrayfire/array.pyc in __init__(self, src, dims)
    133                 type_char = tmp.typecode
    134             else:
--> 135                 raise TypeError("src is an object of unsupported class")
    136 
    137             elements = 1

TypeError: src is an object of unsupported class
```

**Comment by pavanky** [comment]
We are trying to ensure ArrayFire works out of the box on a python distribution. Numpy may not always be installed on the machine. That said, I pushed out 14d5bc641353f4ef14d798eed2e6aeb684d7a298 that should add the ability to interop with numpy in the following manner:

```
import numpy as np
import arrayfire as af

def af_array(src, transpose=False):
    res = af.array(src.ctypes.data, src.shape, src.dtype.char)
    return res if not transpose else af.transpose(res)

a = np.random.random((5,5))
b = af_array(a)

print(a)
af.display(b)
```

**Comment by pavanky** [comment]
The transpose flag may be necessary because numpy is row major by default and ArrayFire is column major.

**Comment by cmey** [comment]
Works great, thanks!

**Comment by mklf** [comment]
This only work for square matrix, for example:
```python 
import numpy as np
import arrayfire as af

def af_array(src, transpose=False):
    res = af.array(src.ctypes.data, src.shape, src.dtype.char)
    return res if not transpose else af.transpose(res)

a = np.random.random((2,3))
b = af_array(a,transpose=True)

print(a)
af.display(b)
```
will print:
```python 
Using cuda backend
[[ 0.25789153  0.03512506  0.46146956]
 [ 0.72702506  0.40743834  0.89003303]]
b
[3 2 1 1]
    0.2579     0.0351 
    0.4615     0.7270 
    0.4074     0.8900 
```
a solution to this is convert the numpy.ndarray to fortran order first:
```python 
import numpy as np
import arrayfire as af

def af_array(src):
    src_ = src if np.isfortran(src) else np.asfortranarray(src)
    res = af.array(src_.ctypes.data, src_.shape, src_.dtype.char)
    return res
```

**Comment by pavanky** [comment]
@FilipeMaia Can you comment here on how you are achieving this in afnumpy ?

**Comment by pavanky** [comment]
This is actually present in master as a constructor thanks to @FilipeMaia 

The lay out changes are going to be difficult to implicitly handle inside arrayfire. I think it should be left to the user to change it to proper format before calling arrayfire functions.

**Comment by FilipeMaia** [comment]
The only way to ensure a conversion where the dimensions of the arrayfire array match dimensions of the numpy is like @mklf did in the last code snippet (N.B. this often means the data will have to be transposed as numpy uses C order by default).

In afnumpy I'm currently assuming the numpy arrays are always in C order and have the shape of the arrayfire array be the inverse of the numpy array, e.g.:
```
# Assuming src is in contiguous C order
A = af.array(src.ctypes.data, src.shape[::-1], src.dtype.char)
```

**Comment by pavanky** [comment]
I closed the issue hastily. arrayfire --> numpy is supported but the opposite is not.

**Comment by pavanky** [comment]
This is fixed in master. All you need to do now is call the following function:

```
af_arr = af.np_to_af_array(np_arr)
```

This will take care of all cases @mklf mentions.

**Comment by cmey** [comment]
Thank you!

**Comment by pavanky** [comment]
@cmey I have uploaded the latest version to be available via `pip`
