### ISSUE TITLE
__del__() in loops

### ISSUE THREAD

**Issue by ZacDiggum** [arrayfire/arrayfire-python#70]
Whenever I call `some_array.__del__()` inside a loop, the loop executes only once and then gets terminated in silence. What does `__del__()` actually do behind the scenes? I tried to get rid of `some_array = None`.

**Comment by pavanky** [comment]
@ZacDiggum can you show me some code to reproduce this ?

**Comment by ZacDiggum** [comment]
something like this:
```
for i in range(10):
    a = af.randu(5,5)
    a.__del__()
    print("I'm still alive in step %i."%i)
```
Stops after step 0.

**Comment by FilipeMaia** [comment]
Looks like `Array.__del__()` should set `self.arr.value` to 0 after `af_release_array`.

**Comment by ZacDiggum** [comment]
Inserting `self.arr.value=0` after the call to `af_release_array` finishes the loop but gives an error when accessing the array afterwards.

**Comment by FilipeMaia** [comment]
Accessing the array after deleting it? That doesn't make sense.

**Comment by ZacDiggum** [comment]
I know, I just tried it out. The name of the array somehow is still around. When inserting `print(a)` as last line in the loop, I expected an 'a is not defined' message. Instead I got a crash. I thought, `.__del__()` would clean up everything about the array. That's all.

**Comment by pavanky** [comment]
@ZacDiggum That's a python thing.. You could try that with other python objects and you would still see the same issue.
