### ISSUE TITLE
upgrade problems

### ISSUE THREAD

**Issue by ZacDiggum** [arrayfire/arrayfire-python#74]
Hi there,
today I upgraded af_python via pip. I uninstalled the devel version previously installed with setup.py install. Then installed with pip. Afterwards I tried to do simple_tests.py from the devel package. I got 'Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.' My af-python based application executes without any result, no error message, no sign of doing calculations, no nothing. I also reinstalled the arrayfire library from the website, without any success. af.info() on the other hand works and gives the version and device message. What's going on here? Is there a way to explicitly point af_python to the arrayfire path?

**Comment by shehzan10** [comment]
So `mkl_intel_thread.dll` is a dependency of MKL that is loaded when needed. That is, it won't error out if it is not found in path when the application starts. The application is allowed to run until the dll is required to be loaded. That's why you are seeing af.info work fine.

Can you ensure that the examples shipped with ArrayFire are working correctly? There are prebuilt examples in `AF_PATH/examples/benchmarks` that you can run to confirm.

**Comment by ZacDiggum** [comment]
Okay, I got it. Stupid me. In the pip version of af_python as well as in the devel branch the issue concerning `.__del__()` #70 is unchanged. FilipeMaya suggested setting the array value to 0 after releasing. I did that myself in my distro and del worked that way. Inserting `self.arr.value = 0` as last line in del solves the problem. Could you change it in the source?

**Comment by pavanky** [comment]
Hmm, I am not sure how this is affecting MKL..

**Comment by ZacDiggum** [comment]
I get the mkl message when executing simple_tests.py. I tried to change the backend to cpu in my code (at the very beginning) but I get an error message:
```
Traceback (most recent call last):
  File "test_af.py", line 5, in <module>
    af.set_backend('cpu')
  File "C:\winpython35\python-3.5.1.amd64\lib\site-packages\arrayfire-3.4.0-py3.5.egg\arrayfire\library.py", line 534, in set_backend
    raise RuntimeError("Can not change backend after loading %s" % name)
RuntimeError: Can not change backend after loading cpu
```

**Comment by pavanky** [comment]
@ZacDiggum switching the backend should be the first thing you do in the code for now.

Is the MKL error happening anytime you run `simple_tests.py` ?

**Comment by ZacDiggum** [comment]
I'm changing the backend as very first statement after the imports (line 5) and I get the error.
simple_tests shows me all tests passed and the mkl message comes as last line of output. Every time.

**Comment by ZacDiggum** [comment]
I inserted `af.set_backend('cpu',unsafe=True)` as first line in bench_blas.py. I get the mkl error and the script crashes.

**Comment by pavanky** [comment]
@ZacDiggum do you have other versions of MKL installed on your system by any chance?

**Comment by ZacDiggum** [comment]
Scilab comes with mkl but the path isn't exposed system-wide. It's just in the Scilab folder.

**Comment by ZacDiggum** [comment]
Nope, that wasn't it. I uninstalled Scilab and reinstalled af again. No changes.

**Comment by ZacDiggum** [comment]
I should mention that afpath/examples/benchmarks/blas_cpu.exe works flawless.

**Comment by pavanky** [comment]
@ZacDiggum Can you print the output of `af.info()` from python and `af::info()` from c++ ?

**Comment by ZacDiggum** [comment]
af.info() and blas_cpu.exe both give
```
ArrayFire v3.3.1 (CPU, 64-bit Windows, build f53efc3)
[0] Intel: Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz, 4094 MB, Max threads(4)
```

**Comment by pavanky** [comment]
@ZacDiggum What python distribution are you using ?

**Comment by ZacDiggum** [comment]
Python 3.5.1. It's a 'portable' distro ([Winpython](https://winpython.github.io)), but python path is in the environment variables. Custom changes include installing af_python and afnumpy as well as the most recent numpy+mkl from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy). Numpy+mkl also distributes mkl libs in its `core` directory. This is the second occurrence of mkl on my system I hadn't thought of before. But that also worked 'til yesterday.

**Comment by ZacDiggum** [comment]
Arrayfire's mkl is v11.3.1.1 and numpy's mkl is v11.3.2.1...But numpy shouldn't expose it's core folder to any paths outside.

**Comment by shehzan10** [comment]
Yeah I was suspecting that there might be a different copy of MKL.
MKL loaded the dlls from local files. So if ArrayFire was picked up by the numpy MKL, then its going to try and load the numpy thread.dll (which may not be present).

One way to be sure is to use Process Explorer. Put a pause in your af-python project and check the application in Process Explorer. It should be able to tell you the DLL that has been loaded.

**Comment by ZacDiggum** [comment]
I'll try that in a sec. But `mkl_intel_thread.dll` is present in the numpy folder. That's where I got the version number from.

**Comment by shehzan10** [comment]
So maybe it's trying to load the specific version of thread.dll which is causing a mismatch? I think there was a previous issue that some other user was having similar to this (not with python/numpy though)

**Comment by ZacDiggum** [comment]
Hm, numpy 1.10.4 also ships with mkl 11.3.2.1. Now I'm back to my originally working config with the only difference being the update of af_python.

**Comment by ZacDiggum** [comment]
I'm giving up for now. OpenCL backend works and CPU backend works also for everything non-MKL. My config now is af v3.3.1, af_python v3.4, Numpy+mkl v1.11.0, Python v3.5.1. If you have any further ideas or want me to try something out, let me know.

**Comment by ZacDiggum** [comment]
Okay, I did a funny thing. I copied all MKL files from numpy (newer) into af's lib (older) directory. Now it seems to work. Plus I have a newer MKL version within af now. :-)

**Comment by ZacDiggum** [comment]
I read the MKL 11.3.2 release notes. The first point states:

> Introduced mkl_finalize function to facilitate usage models when Intel MKL dynamic libraries or third party dynamic libraries are linked with Intel MKL statically are loaded and unloaded explicitly.

Could that be helpful with keeping two MKL installations separate?

**Comment by shehzan10** [comment]
I don't think that's relevant here. [mkl_finalize documentation](https://software.intel.com/en-us/node/610261).

Neither do we link statically nor do we load/unload explicitly. It's what MKL does internally.

**Comment by ZacDiggum** [comment]
I see. Should I close this issue since it's more of a python+numpy+arrayfire related conflict?

**Comment by pavanky** [comment]
We should perhaps look into reproducing this and try and fix it properly..

**Comment by pavanky** [comment]
@ZacDiggum can you give one last info on what arrayfire-python works and what doesn't ?

From what I can tell devel is working but the latest release from master isn't ?

**Comment by ZacDiggum** [comment]
Devel is working, the problem was my usage of `.__del__()` without setting the value to 0 after release. I changed it and my app is working again. The problem is the conflict between the MKL files in Arrayfire and the ones in the MKL enabled Numpy from Christoph Gohlke's website. It seems like the MKL inside Numpy is picked up first and that prevents the CPU backend from loading its own MKL dlls properly. I copied the MKL from Numpy (which is a newer version, v11.3.2) over to Arrayfire and now it works. You could reproduce the error by installing Numpy+MKL on a Windows box ([Link](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy)) I guess.

**Comment by pavanky** [comment]
OK. I think the problem can only be fixed in upstream arrayfire library by using a static library or by using [side by side assembly](https://msdn.microsoft.com/en-us/library/windows/desktop/ff951640(v=vs.85).aspx).
