### ISSUE TITLE
Crashes when running on Travis

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire-python#75]
I'm getting unexplained crashes when running on Travis, which makes debugging hard.
The following commit FilipeMaia/arrayfire-python@12a345d1607de11071ebf0ab8115fd4c3ddd620b (which is basically devel plus adding Travis using a small fft2 benchmark test) sometimes cases the crash (but it's not deterministic).
You can find an example of the crash at https://travis-ci.org/FilipeMaia/arrayfire-python/jobs/121102341 (including a backtrace).

I've started seeing this on my afnumpy tests and was trying to dig deeper, but I can't reproduce this on my local systems. Any ideas would be most appreciated...

**Comment by FilipeMaia** [comment]
And now a core dump with line numbers:
https://travis-ci.org/FilipeMaia/arrayfire-python/jobs/121111434

**Comment by shehzan10** [comment]
One thing I noticed is that you are doing `cd ${HOME}/build/FilipeMaia/arrayfire-python`.

Shouldn't it be without the build, ie  `cd ${HOME}/FilipeMaia/arrayfire-python`? Cuz the cd command seems to be the first point of failure.

**Comment by FilipeMaia** [comment]
The `cd` is correct. Why do you say it is the first point of failure? In both cases you have:
`The command "cd ${HOME}/build/FilipeMaia/arrayfire-python" exited with 0.`

**Comment by shehzan10** [comment]
Oh my bad. I ignorantly mistook it to be an error. 

I'm not completely sure whether debug built type disables the CPU async, so you could try adding `-DBUILD_CPU_ASYNC=OFF` when building arrayfire.

**Comment by FilipeMaia** [comment]
Turning off cpu async seems to resolve the issue. Looks like it's not be a tricky issue to track...

**Comment by pavanky** [comment]
@FilipeMaia can we close this issue?

**Comment by FilipeMaia** [comment]
Yes absolutely.
