### ISSUE TITLE
examples/graphics - "OS call failed"

### ISSUE THREAD

**Issue by bscully** [arrayfire/arrayfire-python#78]
In the example files (surface, conway, etc), I am unable to run them due to an error:

runfile('C:\\Users\\Ben\\Desktop\\surface.py')
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-19d8454c12e0>", line 1, in <module>
    runfile('C:\\Users\\Ben\\Desktop\\surface.py')
  File "C:\Eclipse\plugins\org.python.pydev_4.3.0.201508182223\pysrc\pydev_umd.py", line 167, in runfile
    execfile(filename, namespace)
  File "C:\Users\Ben\Desktop\surface.py", line 26, in <module>
    win.surface(x, y, z)
  File "C:\Python27\lib\site-packages\arrayfire\graphics.py", line 240, in surface
    ct.pointer(_cell)))
  File "C:\Python27\lib\site-packages\arrayfire\util.py", line 75, in safe_call
    raise RuntimeError(to_str(err_str))
RuntimeError: In function cudaGraphicsResource *cuda::InteropManager::getBufferResource(const fg::Surface *)
In file C:/workspace/graphics-inst-src/src/backend/cuda/interopManager.cu:130
CUDA Error (63): OS call failed or operation not supported on this OS

Python2.7 64 bit (standalone distribution)
Windows 7 64 bit

latest pip install - as of 4/27/2016 @10pm EST.   pip list shows "arrayfire (3.3.20160427.post1)"

**Comment by shehzan10** [comment]
There should be precompiled examples in the AF_PATH/examples/graphics directory. Can you try running those?

Note: For CUDA examples, you will need to copy the NVVM DLL or add it to PATH.

**Comment by pavanky** [comment]
@bscully do you have the display connected to the NVIDIA GPU ?

**Comment by bscully** [comment]
surface_cpu.exe ran and an animated plot appeared.
surface_gpu.exe gave this error, "
C:\Program Files\ArrayFire\v3\examples\graphics>surface_cuda.exe
ArrayFire v3.3.2 (CUDA, 64-bit Windows, build f65dd97)
Platform: CUDA Toolkit 7.5, Driver: CUDA Driver Version: 7050
[0] GeForce GT 610, 2048 MB, CUDA Compute 2.1
60 60 1 160 60 1 1
ArrayFire Exception (Internal error:998):
In function cudaGraphicsResource *cuda::InteropManager::getBufferResource(const fg::Surface *)
In file C:/workspace/graphics-inst-src/src/backend/cuda/interopManager.cu:130
CUDA Error (63): OS call failed or operation not supported on this OS

In function void __cdecl af::Window::surface(const class af::array &,const class af::array &,const class af::array &,const char *const )
In file src\api\cpp\graphics.cpp:117


I both added nvvm64_30_0.dll to AF_PATH/examples/graphics  as well as to the PATH.  (and then restarted cmd)

**Comment by bscully** [comment]
I do not, my display is connected to another driver

**Comment by pavanky** [comment]
@bscully We do not have a graphics fallback option in CUDA backend. You need the display connected to the NVIDIA GPU

**Comment by bscully** [comment]
Thanks!

I suggest a more detailed error message or a check for this scenario, it cannot be that uncommon.

On Apr 27, 2016, at 11:27 PM, Pavan Yalamanchili <notifications@github.com<mailto:notifications@github.com>> wrote:


@bscully<https://github.com/bscully> We do not have a graphics fallback option in CUDA backend. You need the display connected to the NVIDIA GPU

-

**Comment by pavanky** [comment]
@bscully I agree. We'll need to fix it upstream. I am closing the issue here.
