### ISSUE TITLE
__array_priority__ regression

### ISSUE THREAD

**Issue by ZacDiggum** [arrayfire/arrayfire-python#81]
Hi,
I just installed the third v3.3 bugfix release. The problem with adding / multiplying numpy scalars and af arrays somehow came back. See the discussion with @FilipeMaia, issue #69.
Try something like:
```
a = af.randu(5,5)
b = np.sin(1)*a
```
b will be a numpy array. Back then, Filipe changed the `__array_priority__` attribute.

**Comment by ZacDiggum** [comment]
I just noticed this only happens in the version with [this version](https://github.com/arrayfire/arrayfire-python/releases/tag/3.3.2016010) which is master, I guess. Devel works fine.

**Comment by pavanky** [comment]
@ZacDiggum I don't think I ever merged that into master.. That PR was sent to devel.

**Comment by ZacDiggum** [comment]
:-) Are you going to merge it?

**Comment by pavanky** [comment]
@ZacDiggum I am going to do it. I have come across a couple of other minor issues as well that need to be resolved.

**Comment by pavanky** [comment]
I'll close it when the issue is resolved. Makes sure I am keeping track of things :)

**Comment by pavanky** [comment]
Ok this is now fixed :) sorry about the delay. I hit a bug when testing with unified backend and it ended up being an upstream bug in arrayfire itself :)
