### ISSUE TITLE
could not find function af_get_active_backend in library

### ISSUE THREAD

**Issue by maodayezheng** [arrayfire/arrayfire-python#83]
Hello ! I am trying to create an Julia ArrayFire wrapper by following this python implementation, but I got a small error when I trying to call af_get_active_backend function. The error message says that "could not find function af_get_active_backend in libaf". So I am just wondering where can I actually find this function ?

**Comment by pavanky** [comment]
@maodayezheng There are two: `af.backend.name` and `af.get_backend()`
