### ISSUE TITLE
Create Non Owner Array

### ISSUE THREAD

**Issue by landersson** [arrayfire/arrayfire-python#86]
Hi, 

One thing I'd like to be able to do is temporarily wrap a raw CUDA memory buffer as an ArrayFire Array, without having the Array trying to deallocate this buffer when it goes out of scope.
```
if True:
   ar = af.Array(gpu_ptr, shape, 'f', is_device=True)
   # ugly workaround to not have gpu_ptr deallocated when ar goes out of scope
   ar.arr.value = 0 
```
I've been looking around the code a bit without discovering a proper way to achieve this. Did I miss something?  If not, maybe a `is_owner` parameter to the Array constructor could solve this problem?

**Comment by pavanky** [comment]
Hi, 

If you are using PyCUDA, this should already happen when transfer the array to arrayfire using `af.to_array`. If you are allocating using other means, you can always call `af.lock_array(ar)` which ensures arrayfire does not free the memory when array goes out of scope.

**Comment by pavanky** [comment]
And yes I have plans to add a new parameter in the future release. I did not realize this to be a hotly requested feature (it has been requested a few times in the C++ library as well)

**Comment by landersson** [comment]
But `af.to_array` will allocate a new buffer and copy the contents of the given (pycuda) gpu array into that. I'd like to avoid that copy.

**Comment by pavanky** [comment]
@landersson then you can simply call `af.lock_array` after creation. That should take care of what you are asking.

**Comment by landersson** [comment]
Yep, that solves my problem. Thanks!
