### ISSUE TITLE
Test failures on i386

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire-python#89]
The complete build log is available [here](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/python-arrayfire.html).

All errors are of the form:
```
ERROR:root:Traceback (most recent call last):
  File "/build-1st/python-arrayfire-3.3.20160516/tests/simple/_util.py", line 32, in run
    test(verbose)
  File "/build-1st/python-arrayfire-3.3.20160516/tests/simple/arith.py", line 18, in simple_arith
    a = af.randu(3,3)
  File "/build-1st/python-arrayfire-3.3.20160516/.pybuild/pythonX.Y_2.7/build/arrayfire/data.py", line 223, in randu
    safe_call(backend.get().af_randu(ct.pointer(out.arr), 4, ct.pointer(dims), dtype.value))
  File "/build-1st/python-arrayfire-3.3.20160516/.pybuild/pythonX.Y_2.7/build/arrayfire/util.py", line 75, in safe_call
    raise RuntimeError(to_str(err_str))
RuntimeError: In function af::dim4 verifyDims(unsigned int, const dim_t*)
In file src/api/c/data.cpp:42
Invalid dimension for argument 2
Expected: dims[i] >= 1
```
This is using the latest stable releases of AF and AF-Python.

**Comment by ghisvail** [comment]
Any idea where this could come from?

**Comment by pavanky** [comment]
@ghisvail going to set up a 32 bit VM to test this out soon.

**Comment by pavanky** [comment]
@ghisvail 

I tried the following combinations and all of them worked:

- arrayfire devel , python wrapper master - Passed
- arrayfire devel , python wrapper devel - Passed
- arrayfire 3.3.2, python wrapper master - Passed 
- arrayfire 3.3.2, python wrapper devel - Passed 

Can you tell me what combination you are trying ?

**Comment by pavanky** [comment]
I just realized I did not release the latest master on github. I tried the version you are trying (3.3.20160516) and that worked too.

**Comment by pavanky** [comment]
Also tried it with arrayfire v3.3.0. This does not seem to be a problem.

(I have been testing these on a 32 bit ubuntu 16.04 VM)

**Comment by ghisvail** [comment]
I have updated the packaging and the issue does not appear anymore on the [build](http://debomatic-amd64.debian.net/distribution#unstable/python-arrayfire/3.3.20160624-1/buildlog) machine. Not sure what happened on the reproducibility testing machines.

Closing.
