### ISSUE TITLE
"unwrap" function

### ISSUE THREAD

**Issue by mjabri** [arrayfire/arrayfire-python#9]
I looked at the python bindings and could not find the "unwrap" function which is supposed to implement MATLAB im2col like op. Did i miss it? If not are there plans to have it? 
What i am trying to do is a convolution of an image with multiple kernels using a matrix multiplication approach as for example in Caffe. For this, the image needs to be 'lowered' (ie using an im2col like op) so each extracted patch become (raveled) row in a matrix, and the kernels are each a column in the second matrix. After the matrix multiplication, the resulting matrix has to be converted back using a dual 'col2im' op where each column is converted back to an image (convolution output corresponding to same kernel column).

**Comment by pavanky** [comment]
This will done once it is implemented in C++

**Comment by mjabri** [comment]
You mean the "wrap" (col2im) part? Because the im2col part ("wrap") is what is implemented in c++ already.

**Comment by mjabri** [comment]
Ok, i see the confusion. There are two issues, and i really should have raised them separately. So what I am raising here is whether unwrap will be put in the python bindings soon.

**Comment by pavanky** [comment]
@mjabri The "unwrap" function has been added to ArrayFire in the devel branch after 3.0 release. The new functions added during the 3.1 development cycle will be added to the python bindings after 3.1 is released.

**Comment by pavanky** [comment]
This is now present in the master branch.

**Comment by mjabri** [comment]
Thanks!!
