### ISSUE TITLE
Error on af.info()

### ISSUE THREAD

**Issue by dela3499** [arrayfire/arrayfire-python#96]
I just followed the installation instructions, and I got the following error when calling `af.info()`. Any recommendations? 
``` bash
RuntimeError: Error in af_err unified::AFSymbolManager::call(const char*, CalleeArgs ...) [with CalleeArgs = {}]
In file src/api/unified/symbol_manager.hpp:55
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.
```

**Comment by pavanky** [comment]
Did you export `AF_PATH` to point the the arrayfire installation ?

**Comment by pavanky** [comment]
@dela3499 I am closing the issue for now. If you are still facing the issue please let me know.
